import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import Database from 'better-sqlite3';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const db=new Database(path.join(__dirname,'growth.db'));
const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'); db.exec(schema);
const PORT=process.env.PORT||8787;
const WINDSOR_BASE=process.env.WINDSOR_BASE_URL||'https://connectors.windsor.ai';
const KEY=process.env.WINDSOR_API_KEY;
const INSTAGRAM_ACCOUNT=process.env.INSTAGRAM_ACCOUNT_ID||'17841405441798557';
const TIKTOK_ACCOUNT=process.env.TIKTOK_ACCOUNT_ID||'_000ED0TXJfEG1iLh7NHd6nldR-547HZxO6X';
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(obj));};
const n=v=>v==null||v===''?null:Number(v);
function upsert(row){db.prepare(`INSERT INTO content_performance(platform,platform_content_id,content_id,published_at,caption,content_type,permalink,views,reach,engagements,likes,comments,shares,saves,favorites,avg_watch_seconds,skip_rate,completion_rate,new_followers,profile_visits,website_clicks,lead_submissions,raw_json,updated_at) VALUES(@platform,@platform_content_id,@content_id,@published_at,@caption,@content_type,@permalink,@views,@reach,@engagements,@likes,@comments,@shares,@saves,@favorites,@avg_watch_seconds,@skip_rate,@completion_rate,@new_followers,@profile_visits,@website_clicks,@lead_submissions,@raw_json,CURRENT_TIMESTAMP) ON CONFLICT(platform,platform_content_id) DO UPDATE SET content_id=excluded.content_id,published_at=excluded.published_at,caption=excluded.caption,content_type=excluded.content_type,permalink=excluded.permalink,views=excluded.views,reach=excluded.reach,engagements=excluded.engagements,likes=excluded.likes,comments=excluded.comments,shares=excluded.shares,saves=excluded.saves,favorites=excluded.favorites,avg_watch_seconds=excluded.avg_watch_seconds,skip_rate=excluded.skip_rate,completion_rate=excluded.completion_rate,new_followers=excluded.new_followers,profile_visits=excluded.profile_visits,website_clicks=excluded.website_clicks,lead_submissions=excluded.lead_submissions,raw_json=excluded.raw_json,updated_at=CURRENT_TIMESTAMP`).run(row)}
function extractContentId(text=''){return text.match(/NWS-\d{8}-[A-Z0-9-]+-(?:TRADE|NEWS|EDU|RECAP|VIDEO|REEL)-?\d*/i)?.[0]?.toUpperCase()||null}
async function windsor(connector,fields,account,dateFrom,dateTo){if(!KEY)throw new Error('WINDSOR_API_KEY is not configured');const u=new URL('/api/v1.0/data',WINDSOR_BASE);u.searchParams.set('api_key',KEY);u.searchParams.set('connector',connector);u.searchParams.set('fields',fields.join(','));u.searchParams.set('date_from',dateFrom);u.searchParams.set('date_to',dateTo);if(account)u.searchParams.set('accounts',account);const r=await fetch(u);if(!r.ok)throw new Error(`Windsor ${connector}: ${r.status} ${await r.text()}`);const body=await r.json();return Array.isArray(body)?body:(body.data||body.result||[])}
async function sync(days=30){const to=new Date(),from=new Date(Date.now()-(days-1)*86400000);const fmt=d=>d.toISOString().slice(0,10);const igFields=['media_id','media_caption','timestamp','media_type','media_product_type','media_permalink','media_views','media_reach','media_engagement','media_like_count','media_comments_count','media_saved','media_shares','media_reel_avg_watch_time','media_reel_skip_rate'];const ttFields=['video_id','video_caption','video_create_datetime','video_duration','video_views_count','video_reach','video_likes','video_comments','video_shares','video_favorites','video_average_time_watched','video_full_watched_rate','video_new_followers','video_profile_views','video_website_clicks','video_lead_submissions','video_share_url'];const [ig,tt]=await Promise.all([windsor('instagram',igFields,INSTAGRAM_ACCOUNT,fmt(from),fmt(to)),windsor('tiktok_organic',ttFields,TIKTOK_ACCOUNT,fmt(from),fmt(to))]);const tx=db.transaction(()=>{for(const x of ig)upsert({platform:'instagram',platform_content_id:String(x.media_id),content_id:extractContentId(x.media_caption),published_at:x.timestamp,caption:x.media_caption||'',content_type:x.media_type||x.media_product_type||'unknown',permalink:x.media_permalink||'',views:n(x.media_views),reach:n(x.media_reach),engagements:n(x.media_engagement),likes:n(x.media_like_count),comments:n(x.media_comments_count),shares:n(x.media_shares),saves:n(x.media_saved),favorites:null,avg_watch_seconds:n(x.media_reel_avg_watch_time)==null?null:n(x.media_reel_avg_watch_time)/1000,skip_rate:n(x.media_reel_skip_rate),completion_rate:null,new_followers:null,profile_visits:null,website_clicks:null,lead_submissions:null,raw_json:JSON.stringify(x)});for(const x of tt)upsert({platform:'tiktok',platform_content_id:String(x.video_id),content_id:extractContentId(x.video_caption),published_at:x.video_create_datetime,caption:x.video_caption||'',content_type:n(x.video_duration)>0?'video':'post',permalink:x.video_share_url||'',views:n(x.video_views_count),reach:n(x.video_reach),engagements:(n(x.video_likes)||0)+(n(x.video_comments)||0)+(n(x.video_shares)||0)+(n(x.video_favorites)||0),likes:n(x.video_likes),comments:n(x.video_comments),shares:n(x.video_shares),saves:null,favorites:n(x.video_favorites),avg_watch_seconds:n(x.video_average_time_watched),skip_rate:null,completion_rate:n(x.video_full_watched_rate),new_followers:n(x.video_new_followers),profile_visits:n(x.video_profile_views),website_clicks:n(x.video_website_clicks),lead_submissions:n(x.video_lead_submissions),raw_json:JSON.stringify(x)})});tx();db.prepare('INSERT INTO sync_runs(source,status,records,details) VALUES(?,?,?,?)').run('windsor','success',ig.length+tt.length,JSON.stringify({instagram:ig.length,tiktok:tt.length}));return {instagram:ig.length,tiktok:tt.length,total:ig.length+tt.length}}
function dashboard(){const totals=db.prepare(`SELECT COALESCE(SUM(views),0) views,COALESCE(SUM(reach),0) reach,COALESCE(SUM(engagements),0) engagements,COALESCE(SUM(profile_visits),0) profile_visits,COALESCE(SUM(website_clicks),0) link_clicks,COALESCE(SUM(lead_submissions),0) leads FROM content_performance`).get();const platforms=db.prepare(`SELECT platform,COUNT(*) posts,SUM(views) views,SUM(reach) reach,SUM(engagements) engagements,SUM(shares) shares,SUM(saves) saves,SUM(new_followers) new_followers,SUM(profile_visits) profile_visits,SUM(website_clicks) website_clicks FROM content_performance GROUP BY platform`).all();const top=db.prepare(`SELECT platform,COALESCE(content_id,substr(caption,1,60),platform_content_id) label,views,engagements,shares,permalink FROM content_performance ORDER BY views DESC LIMIT 10`).all();const conversions=db.prepare(`SELECT COUNT(*) signups,COALESCE(SUM(CASE WHEN event_type='paid_member' THEN 1 ELSE 0 END),0) paid_members,COALESCE(SUM(revenue),0) revenue FROM conversion_events`).get();return {totals,platforms,top,conversions}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='POST'&&u.pathname==='/api/sync'){return json(res,200,await sync(Number(u.searchParams.get('days')||30)))}if(req.method==='GET'&&u.pathname==='/api/dashboard')return json(res,200,dashboard());if(req.method==='POST'&&u.pathname==='/api/conversions'){let body='';for await(const c of req)body+=c;const x=JSON.parse(body||'{}');db.prepare(`INSERT INTO conversion_events(content_id,event_type,source,event_id,revenue,currency,occurred_at,raw_json) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(source,event_id) DO UPDATE SET content_id=excluded.content_id,event_type=excluded.event_type,revenue=excluded.revenue,raw_json=excluded.raw_json`).run(x.content_id||null,x.event_type||'signup',x.source||'whop',x.event_id||crypto.randomUUID(),Number(x.revenue||0),x.currency||'USD',x.occurred_at||new Date().toISOString(),JSON.stringify(x));return json(res,200,{ok:true})}return json(res,404,{error:'not found'})}catch(e){db.prepare('INSERT INTO sync_runs(source,status,records,details) VALUES(?,?,?,?)').run('api','error',0,String(e));json(res,500,{error:e.message})}});server.listen(PORT,()=>console.log(`Growth Intelligence API on :${PORT}`));
